---
  - name: Instalação HA Proxy
    ansible.builtin.package:
      name:
      - haproxy
      state: present

  - name: Arquivo de configuracao HAProxy
    ansible.builtin.blockinfile:
      path: /etc/haproxy/haproxy.cfg
      block: |

        frontend apiserver
        bind *:6443
        mode tcp
        option tcplog
        default_backend apiserverbackend

        backend apiserverbackend
        option httpchk GET /healthz
        http-check expect status 200
        mode tcp
        option ssl-hello-chk
        balance     roundrobin
  
  - name: Configuração do Loadbalance dos Kube-apiserver (Controlplane)
    ansible.builtin.lineinfile:
      state: present
      dest: /etc/haproxy/haproxy.cfg
      line: "server {{ item }}-kubeapi {{ item }}:6443 check fall 3 rise 2"
    loop: "{{ groups['control'] }}"

  - name: Habilita e Reinicia Serviço HAProxy
    ansible.builtin.systemd:
      name: haproxy
      enabled: true
      state: restarted
