---
  - name: Instalação Keepalived
    ansible.builtin.yum:
      name:
      - keepalived
      state: present

  - name: Criação de Usuário Keepalived
    ansible.builtin.user:
      name: keep
      state: present
      system: true
      create_home: false

  - name: Remover arquivo de configuração original
    ansible.builtin.file:
      path: /etc/keepalived/keepalived.conf
      state: absent

  - name: Criação do Arquivo de Configuração 
    ansible.builtin.file:
      path: /etc/keepalived/keepalived.conf
      state: touch
      mode: u=rw,g=r,o=r

  - name: Arquivo de configuracao Keepalived
    ansible.builtin.blockinfile:
      path: /etc/keepalived/keepalived.conf
      block: |
        global_defs {
            router_id LVS_DEVEL
        }
        vrrp_script check_haproxy {
          script "/usr/sbin/pidof haproxy"
          interval 2
        }

        vrrp_instance VI_1 {
            state SLAVE
            interface ens192
            virtual_router_id 51
            priority 50
            authentication {
                auth_type PASS
                auth_pass 123456!@#
            }
            virtual_ipaddress {
                {{ ipvirtual }}
            }
            track_script {
                check_haproxy
            }
        }

  - name: Habilita e Reinicia Serviço KeepAlived
    ansible.builtin.systemd:
      name: keepalived
      enabled: true
      state: restarted
